name: Disable Default Pages Deployment

on:
  push:
    branches:
      - main  # Set this to your default branch
  workflow_dispatch:

jobs:
  disable-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create empty gh-pages-config file
        # This is a dummy step to create a marker file 
        # indicating we're using custom deployment
        run: |
          touch .github/gh-pages-config
          echo "# Custom GitHub Pages Deployment" > .github/gh-pages-config
          echo "# This site is deployed via a custom workflow" >> .github/gh-pages-config
          echo "# Please check .github/workflows/deploy.yml" >> .github/gh-pages-config
          
      - name: Commit marker file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Mark repository as using custom Pages deployment"
          file_pattern: ".github/gh-pages-config" 